server:
  port: 9000
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/sportequipmentrent
  username: #your username at data base
  password: #password by your data base
mail:
   username: #type your email here
   password: #type your password here
   protocol: smtp
   host: smtp.gmail.com
   port: 587
   charset: UTF-8
   smtp:
       auth: true
       starttls:
           enable: true
           required: true
       debug: true
logging.path: ~/spring