server:
  port: 9000
spring:
 profiles: dev
 datasource:
  url: jdbc:postgresql://localhost:5432/sportequipmentrent
  username: #your username at data base
  password: #password by your data base
mail:
   username: #type your email here
   password: #type your password here
   protocol: smtp
   host: smtp.gmail.com
   port: 587
   charset: UTF-8
   smtp:
       auth: true
       starttls:
           enable: true
           required: true
       debug: true
resources:
   path: #path for your resources on local computer
   images: #path for your images from resources path on local computer

---

server:
  port: 9000
spring:
 profiles:
  active: staging
 datasource:
  url: jdbc:postgresql://localhost:5432/sportequipmentrent
  username: #your username at data base
  password: #password by your data base
mail:
   username: #type your email here
   password: #type your password here
   protocol: smtp
   host: smtp.gmail.com
   port: 587
   charset: UTF-8
   smtp:
       auth: true
       starttls:
           enable: true
           required: true
       debug: true
resources:
   path: #path to your resources on server
   images: #path for your images from resources path on server